# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: ip-pool
spec:
  addresses:
    - 192.168.0.100-192.168.0.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: l2-adv
spec:
  ipAddressPools:
    - ip-pool
