apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: play-ground
servers: 1
agents: 2
ports:
  - port: 8085:80
    nodeFilters:
    - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
        - server:*